### ISSUE TITLE
NONDETERM should never downgrade to MT19337

### ISSUE THREAD

**Issue by simsong** [IntelPython/mkl_random#10]
Because NONDETERM is secure and MT19337 is not, NONDETERM should never downgrade to MT19337.

Apparently calling .seed() on a NONDETERM random number generator will make it downgrade to MT19337. This behavior should be validated and, if it is true, should be removed.

**Comment by oleksandr-pavlyk** [comment]
@simsong Method `.seed(seed_value, brng=brng)` seeds the generator corresponding to `brng` using the `seed_value`. 

`brng` defaults to `'MT19937'` explaining the behavior. 

Your suggestion seems to be change the default to `None` to be interpreted as `MT19937` is called on an instance whose `brng` is yet unset, but otherwise keeping the `brng` of the instance. 

This is sensible. Will implement.

Sorry I did not see the request any sooner.
